export {
  BRAND,
  FEATURE_CALLOUTS,
  VEHICLE_VERDICT,
  WRENCHABILITY_SCORE_EXPLANATION,
  buildCompareHighlights,
  buildVehicleScoreSummary,
  countRows,
  formatRepairNameList,
  getBestOverallText,
  getCategoryLabelFromAverage,
  getCommonRepairCoverageDescription,
  getCoverageInfoFromRepairCount,
  getCoverageLabelClass,
  getScoreBasedSummary,
  getVehicleCoverageInfo,
  getVehicleQuickTake,
  getVehicleVerdict,
  scoreClass,
  selectAllRows,
} from './appHelpers'
